language: python
python:
  - "3.9"
install:
  - pip install -r requirements_travis.txt
script:
  - python -m compileall .
  - pycodestyle .
  - python -m flake8 .
  - python -m pip install --root=build install -e .
  - ls -laR build
