language: python
python:
  - "3.9"
install:
  - pip install -r requirements_ci.txt
script:
  - python -m compileall mumailer
  - python -m pycodestyle mumailer
  - python -m flake8 mumailer
  - python -m build --outdir=dist .
  - python -m pip install --verbose dist/*.whl
  - python -m pip list
  - python -m pip freeze
  - mumailer --help
  - mumailer --version
  - ls -laR .
  - python -m pip uninstall --yes --verbose mumailer
